CREATE TABLE advisor (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT UNSIGNED UNIQUE,
    teacher_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_advisor_student FOREIGN KEY (student_id) REFERENCES student(id)
    ON DELETE SET NULL,
    CONSTRAINT fk_advisor_teacher FOREIGN KEY (teacher_id) REFERENCES teacher(id)
    ON DELETE SET NULL
);