CREATE TABLE account (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    student_id BIGINT UNSIGNED DEFAULT NULL UNIQUE,
    teacher_id BIGINT UNSIGNED DEFAULT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT fk_account_student FOREIGN KEY (student_id) REFERENCES student(id)
    ON DELETE SET NULL,
    CONSTRAINT fk_account_teacher FOREIGN KEY (teacher_id) REFERENCES teacher(id)
    ON DELETE SET NULL
);
